name: gh-pages publisher 🚀

on:
push:
  branches: [ master ]

jobs:
publish-gh-pages:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install --frozen-lockfile
    # - run: git config user.name "<user name>" && git config user.email "user email"
    - run: yarn run deploy
  env:
    GH_TOKEN: ${{secrets.SECRET_GITHUB_TOKEN}}