name: gh-pages publisher 🚀

on:
  push:
    branches: [ main ]

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: git config user.name "River Delta Bot" && git config user.email "76537137+riverdelta-bot@users.noreply.github.com"
      - run: yarn deploy
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}